### ISSUE TITLE
YoutubeAds存在问题，部分url无法匹配

### ISSUE THREAD

**Issue by m1a1y1u1e1** [Maasea/sgmodule#11]
![image](https://user-images.githubusercontent.com/34541060/199440047-0435ea23-99a9-456b-a8e9-772ca291f8fd.png)

**Comment by Maasea** [comment]
因为sgmodule 中我添加了新的 url 重写，你只更新了sgmodule文件，还需要更新脚本资源。

**Comment by m1a1y1u1e1** [comment]
不是只需要添加一个YoutubeAds.sgmodule么，没找到其他包含规则的重写呀，麻烦大佬指个路

**Comment by Maasea** [comment]
可能我没表达清楚，你找到surge的外部资源->全部更新

**Comment by m1a1y1u1e1** [comment]
明白了，谢谢
