### ISSUE TITLE
大佬求教YouTube脚本如何去除PIP播放

### ISSUE THREAD

**Issue by ChiefFucker** [Maasea/sgmodule#16]
因为脚本改的貌似不太稳定，我是美区自带这个功能，所以怎样去除脚本里的PIP播放？要是太麻烦的话就不用了，多谢。

**Comment by Maasea** [comment]
怎么不稳定？

**Comment by Maasea** [comment]
我并未复现

如果YouTube 不是最新版，可以尝试更新以下

你可以把 `player` 去掉，但是也失去了去广告功能
