### ISSUE TITLE
protobuf file

### ISSUE THREAD

**Issue by ErfanM98** [Maasea/sgmodule#18]
There are no descriptions about the `proto` files. How to get theme and use them in different sections. It seems that the `.proto` files are not related to Youtube messages or maybe I am in a wrong way. Please help thank you.

**Comment by Maasea** [comment]
You can use the protoc command-line interface (CLI) to decode raw protobuf data and try to interpret its meaning or purpose.

**Comment by ErfanM98** [comment]
I have used the CLI but the proto contains a lot of vauge information and the CLI only prints them. What I am looking for is a schema for decoding the messages. 
And is the `response.proto` file related to Youtube?
