### ISSUE TITLE
There's been a problem !

### ISSUE THREAD

**Issue by harryngne** [Maasea/sgmodule#20]
currently youtubeads can't see the video and it rotates loading but still loads the comments and the videos just can't be viewed

**Comment by Maasea** [comment]
The latest version [18.19.1] of the Youtube app is not reproduced

**Comment by harryngne** [comment]
> The latest version [18.19.1] of the Youtube app is not reproduced

So we have no way to solve it?

**Comment by Maasea** [comment]
You haven't provided any useful information and I haven't reproduced it.

You can close another scripts to prevent conflicts.

**Comment by Maasea** [comment]
Closed due to no reply for a long time.

**Comment by isahwn** [comment]
这个问题可以复现的，目前 YouTube App v18.25.1

> The latest version [18.19.1] of the Youtube app is not reproduced

**Comment by Maasea** [comment]
> 这个问题可以复现的，目前 YouTube App v18.25.1
> 
> > The latest version [18.19.1] of the Youtube app is not reproduced

如果可以复现，在 tg 上联系我 https://t.me/BlveRiv

需要提供详细信息
