### ISSUE TITLE
YouTube on Apple TV

### ISSUE THREAD

**Issue by yiwenleo** [Maasea/sgmodule#21]
大佬你好，可以添加对Apple TV上面YouTube的去广告支持吗？谢谢！

**Comment by Maasea** [comment]
Apple TV 使用 HTTP3 进行数据传输，现有的代理工具不支持MITM，所以无法去除Apple TV的广告

**Comment by ryanfwy** [comment]
最近在研究Surge tvos上Youtube广告的问题，翻到了这个issue，看请求tv端确实应该都是走HTTP3了。
试着强制回退到HTTP2/HTTP1.1，但是也不好使视频播放不了。
`AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT-NO-DROP`

不知道还有没有其他办法呢？

**Comment by Maasea** [comment]
> 最近在研究Surge tvos上Youtube广告的问题，翻到了这个issue，看请求tv端确实应该都是走HTTP3了。 试着强制回退到HTTP2/HTTP1.1，但是也不好使视频播放不了。 `AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT-NO-DROP`
> 
> 不知道还有没有其他办法呢？

我没有 Apple TV 进行测试，但已经有人给出结果了。  见[链接](https://t.me/Loon0x00/1898342)
