### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by haluzt** [Maasea/sgmodule#22]
最近一个礼拜开始，视频经常无法播放，试过换账号，app重装、降级，换节点
都无效，重启手机又好播放了，但过个1天左右又不能放了，只能重启手机。
![93384A27-726E-4D88-8BFE-09837495F2E6](https://github.com/Maasea/sgmodule/assets/46881453/ae942b6a-bccc-4d72-bfc8-11ae1aac32c2)

**Comment by Maasea** [comment]
1. 排除与其他规则混用冲突的情况，关闭其他YouTube相关的所有重写和脚本。
2. 提供出现错误时v1/player 请求的详情，特别是备注部分。
3. 检查有没有YouTube脚本相关的日志产出，有的话也一并提供

**Comment by Maasea** [comment]
长时间未提供有效信息
