### ISSUE TITLE
UDP 转发时无法去除 YouTube 广告

### ISSUE THREAD

**Issue by CraKeyBoy** [Maasea/sgmodule#23]
如题，用的小火箭，pip 和后台播放很少会生效，页面没有广告，翻译功能也好使，偶尔没有中文简体翻译。首次观看视频会有一次广告。
参考大佬的脚本自制的小火箭模块。
https://raw.githubusercontent.com/CraKeyBoy/Script/main/YouTubeAd.sgmodule
也帮忙看看有什么不对的地方、万分感谢🙏

小火箭用的去广告配置
https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_banlist_ad.conf

目前用的youtube 版本是 18.32.2

**Comment by Maasea** [comment]
修改的 sgmodule 看上去没什么问题，但是Shadowrocket规则如何去写我不太清楚，脚本在编写的也没有进行单独测试。

如果播放的时候没有广告，但是 PIP 和后台很少生效，可能是Shadowrocket不支持同时处理 request 和 response ? 

你可以删掉下面 youtube.request 这一行，其他不变
```
youtube.request.beta=type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence)\?,requires-body=1,binary-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.request.beta.js
```
_这样做可能会增加脚本的执行时间，但是在去广告的效果上区别不是很大_

你也可以去找相关的 tg 群组寻求帮助，或者更换 App 测试。比如，Surge 现在有 7 天免费试用。

**Comment by CraKeyBoy** [comment]
好的，非常感谢。我这边验证一下。

**Comment by CraKeyBoy** [comment]
这边试了一下，没有改善。先关闭了。

**Comment by Maasea** [comment]
关闭 UDP 转发是因为：在某些代理场景下，Youtube 有时候会使用 quic 协议进行通信（比如 Tun  模式 ）。

在这种场景下脚本并不会执行。如果不想取消 UDP 转发，可以阻止 Youtube 的 UDP 请求让其回退到 TCP，比如使用下面的逻辑规则
```
  AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT-DROP
```
因为逻辑规则并不是所有代理工具都支持，所以并没有在配置文件中体现。

至于播放页出现广告仍然是不符合预期的。如果是偶现应该是去广告遗漏（经过了多个版本的更新，已经很久没见到了），如果总能出现，应该是脚本执行出现问题了。

**Comment by liweilalala** [comment]
同shadowrocket的后台播放不生效，loon和quantumultx都可以
