### ISSUE TITLE
部分视频无法点开

### ISSUE THREAD

**Issue by ChiefFucker** [Maasea/sgmodule#24]
在搜索列表中观看一个视频后，会出现列表里某个视频打不开的问题，点击没反应，只有点击视频主的头像进入频道才能看。我不确定是代码的问题还是app的问题。
还有一点，我的ip被谷歌定位到中国了，然后画中画偶尔会失效。

**Comment by Maasea** [comment]
1. 无法播放的问题需要提供更多信息，比如报错信息，请求记录。
2. 我没有类似的IP，所以无法复测。如果IP为中国时，返回体的结构不同的话，可能会出现你说的情况。

**Comment by Maasea** [comment]
日志的截图只是surge的日志，没有什么帮助

如果无法播放，最近请求日志应当关注 `v1/player` 这个请求。
