### ISSUE TITLE
Youtube 6/6 beta version compatibility issues & Return to the previous version

### ISSUE THREAD

**Issue by wqh227** [Maasea/sgmodule#27]
1、在23/6/6更新的新sgmodule包括[YoutubeAds.Beta.sgmodule]和[YoutubeAds.sgmodule]版本和新[youtube.beta.js][youtube.request.beta.js][youtube.response.beta.js]脚本对shadowrocket软件无法兼容。
2、旧版本的[youtube.js]由于仓库修改了文件位置从[YouTube/youtube.js]到[YouTube/dist/youtube.js]目录故导致文件无法刷新，或者脚本版本错乱，这会导致app内所有内容不加载，或者脚本失效无法使用。 解决方案： 使用第三方备份的[脚本](https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/modules/YouTubeAd.sgmodule)， 并且手动修改js文件的地址， 目前旧版本还没有失效， 还可以正常使用， 如果某些时候不能拦截广告，搭配[这个](https://raw.githubusercontent.com/Infatuation-Fei/rule/main/Shadowrocket/Module/YouTubeAds.sgmodule)脚本。

**Comment by Maasea** [comment]
我去小火箭上试了一下，你的第一个问题我没复现，完全可以正常运行

第二个问题应该是一些搬运的同学，将模块适配小火箭后没及时更新脚本地址导致的。我并没有提供小火煎的模块配置信息，但是我注释里给出了说明。

至于提供的第二个脚本链接，里面reject 的链接应该是从 devineangine 那里合并过来的。但实际上我的脚本正确执行的时候，根本不会出现里面的几条广告请求。里面那条重定向可能还会影响脚本正常执行，所以最好不要一起使用。

下面给出小火箭的可以使用的模块：
```
```

**Comment by wqh227** [comment]
添加这个的确小火箭马上可以用了， 而且这个新款的广告屏蔽得很彻底👍👍👍
