### ISSUE TITLE
YouTubeads模块在最新测试版Surge下失效

### ISSUE THREAD

**Issue by DockerCS** [Maasea/sgmodule#28]
pip功能用不了，广告好像也不去不了

Surge版本如图：
![image](https://github.com/Maasea/sgmodule/assets/26867628/115f842b-a1e0-4cb4-8237-bea4655c84c3)

**Comment by Maasea** [comment]
Surge 在 TF 5.21.0(2887) 中默认开启了 TUN 模式，导致视频播放的请求走了 QUIC 协议。

现在模块中新增了一条规则，更新最新模块后将恢复正常。
