### ISSUE TITLE
这回应该是全失效了……

### ISSUE THREAD

**Issue by ChiefFucker** [Maasea/sgmodule#29]
最近油管玩命治理屏蔽广告的，这个代码算是坚持的久一点了的，别人的早都不能用了。
而且今天iOS更新，surge也更新，也说不上是哪的问题。。没有生成日志，代码也正常运行。

这谷歌确实抽风，我个人用三年的IP给我送中了…关键是我啥也没干而且别的软件都没事，唯独谷歌给我搞了，真是跳出一道墙谁成想还有墙。

**Comment by Maasea** [comment]
#28
