### ISSUE TITLE
更新后YouTube studio主页加载不出来

### ISSUE THREAD

**Issue by ChiefFucker** [Maasea/sgmodule#33]
用surge看YouTube只会匹配response的代码，所以没有影响，但是YouTube studio会同时匹配request的代码，主页就加载不出来了。我把request删掉了只用response好像也没啥影响，不知道那个代码是做什么用的。不知道是不是bug啊，就是说一下……

**Comment by Maasea** [comment]
YouTube 也会匹配request脚本。不太清楚你为什么没有匹配。

request 脚本用于去除广告的跟踪标记，去除该标记后response中不会包含广告信息，可以减少response的大小。使整体耗时减少200ms左右。

本身response脚本已经具备去除广告的能力，删掉request后，除了增加一点耗时外没什么影响。

**Comment by Karmylr** [comment]
> request 脚本用于去除广告的跟踪标记，去除该标记后response中不会包含广告信息，可以减少response的大小。使整体耗时减少200ms左右。

现在似乎没有request了，是什么原因呢
