### ISSUE TITLE
youtube去广告失效且偶尔提示出错

### ISSUE THREAD

**Issue by Light8r** [Maasea/sgmodule#34]
ios17.2  shadowrocket2.2.41(2093) youtube18.49.3 
尝试REJECT-200 和RECJECT-IMG均有广告，且广告播放完后视频无法正常播放 提示出错重试
经尝试 进度条拉到缓存外的时候同样会提示出错重试
请问有什么解决方法嘛

**Comment by Maasea** [comment]
替换reject的时候需要把下面删掉。详细见#27

一直出现问题的话可以换其他客户端，据我所知surge，qx，loon都运行的很好。
```
[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data="https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/blank.txt"
```

**Comment by Light8r** [comment]
您好，经测试您在 #27给出的例子可行 失败请重试的原因可能是本地网络不好待我之后排查 非常感谢您的帮助
