### ISSUE TITLE
请问字幕翻译可以单独关闭吗？

### ISSUE THREAD

**Issue by BugGust** [Maasea/sgmodule#35]
系统:iOS16.6.1
Surge版本:5.3.8
模块:Youtube (Music) Enhance
Youtube版本:18.49.3
个人偏爱使用VirgilClyne 的 YouTube双语模块，但和Youtube (Music) Enhance搭配使用会有问题(单独使用双语模块看视频时cc字幕会自动打开，搭配使用看视频就自动关闭了)

**Comment by Maasea** [comment]
你可以尝试调整一下模块执行的优先级

**Comment by BugGust** [comment]
你好，我按要求测试了将双语模块优先级高于Youtube (Music) Enhance的组合，虽然字幕可以自动开启了，但画中画和后台播放就不能正常工作了(去广告工作正常)
这个是我使用的双语字幕模块:[DualSubs: ▶ YouTube](https://github.com/DualSubs/YouTube/wiki/🍿-DualSubs:-▶-YouTube)
麻烦大佬了🙏

**Comment by BugGust** [comment]
> 你可以尝试调整一下模块执行的优先级

你好，我按要求测试了将双语模块优先级高于Youtube (Music) Enhance的组合，虽然字幕可以自动开启了，但画中画和后台播放就不能正常工作了(去广告工作正常)
这是我使用的双语字幕模块:[DualSubs: ▶ YouTube](https://github.com/DualSubs/YouTube/wiki/🍿-DualSubs:-▶-YouTube)
麻烦大佬了🙏

**Comment by Maasea** [comment]
两个模块都需要修改一个链接，二选一

**Comment by BugGust** [comment]
> 两个模块都需要修改同一个请求，二选一

好吧，了解了，谢谢dalao解答

**Comment by BugGust** [comment]
> 两个模块都需要修改同一个请求，二选一

想问问作者大大，后续考虑增加字幕功能吗？单独使用当前版本的Youtube (Music) Enhance每次打开一个新视频都得手动打开字幕，如果该视频没有提供中文还得手动到自动翻译里选择中文，操作很繁琐，如果能自动开启字幕并设置为用户上次设置的语言会更好一点吧。

**Comment by Tulinger** [comment]
感谢大佬！youtube画中画quantumultx可用，以前引用的资源经常失效，所以现在想着把脚本放本地。大佬能不能简单说一下：怎么改一下这里（youtube.request = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence),requires-body=1,max-size=-1,binary-body-mode=1,script-path=）让脚本在本地执行，脚本已经放到本地，但是执行不了。还有这里（[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT）不知道放到圈x配置什么位置，用不用放。

**Comment by Tulinger** [comment]
> 感谢大佬！youtube画中画quantumultx可用，以前引用的资源经常失效，所以现在把脚本放本地。大佬能不能简单地说一下：这里怎么改一下（youtube.request = type=http-request,模式=^https://youtubei.googleapis.com/youtubei/v1/（浏览|下一个|播放器|reel/reel_watch_sequence），需要body = 1，max-size = -1，binary-body-mode = 1， script-path=）脚本放在本地执行，脚本已经放到本地，但是执行不了。还有这里（[Rule] AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT AND ,((DOMAIN,youtubei.googleapis.com),(PROTOCOL,UDP)),REJECT）不知道放到圈x配置什么位置，用不用放。

**Comment by Maasea** [comment]
@BugGust  最新的提交应该可以满足你的要求，支持自动打开字幕翻译，默认是简体中文。

如果你在用 surge TF 版本并支持修改远程模块的传入参数，可以通过长按模块的方式手动修改翻译的语言（当传入的参数为 off 时候关闭自动翻译）。

如果你使用的surge版本不支持修改远程模块的参数，可以新建本地模块手动替换argument 后面的参数为：
```
"{"lyricLang":"zh-Hans","captionLang":"zh-Hans","blockUpload":true,"immersive":true}"
```

**Comment by Maasea** [comment]
@Tulinger  我不是QX 的开发者，所以脚本的使用问题，你应该优先和TG群友沟通或询问QX的开发者而不是来询问 Surge 模块的作者

**Comment by Tulinger** [comment]
谢谢在 2024年2月18日，20:44，Maasea ***@***.***> 写道：﻿
@Tulinger  我不是QX 的开发者，所以脚本的使用问题，你应该优先和TG群友沟通或询问QX的开发者而不是来询问 Surge 模块的作者
