### ISSUE TITLE
最近两天自动更新后发现的bug

### ISSUE THREAD

**Issue by wqh227** [Maasea/sgmodule#38]
1.YouTube music歌词在屏蔽广告后的歌曲无法点击和滚动使用，会被锁定（点击下一曲按钮时才会复现，貌似是云控的，降级YouTube music也无效）。
2.YouTube&YouTube music的Airplay投射在屏蔽广告后有概率无法正常播放，会被暂停，必须手动点击播放（自动播放的时候会出现，手机端本地播放不受影响）。
3.YouTube music的升级页面和按钮没有被屏蔽，YouTube的页面广告没有被屏蔽， 我还有一台没有升级YouTube&YouTube music的手机是可以屏蔽的。
最后：也不知道是不是和小火箭有关，Surge实在太贵了，所以麻烦大佬测试一下是不是兼容性问题。

**Comment by Maasea** [comment]
根据描述更新到了最新的 Youtube Music 客户端并进行了测试，并使用surge 进行测试
1. 未复现
2. 复现
3. 未复现

问题 2 暂时无法解决，但你可以让Youtube （Music） 后台播放，在这样的场景下切换 airplay 可以不被暂停。
对于问题1和3，先检查你自身的配置，去掉其他YouTube相关的重写。 依旧不行更换 app 测试

**Comment by wqh227** [comment]
谢谢大佬的测试，我已经准备换软件了，小火箭这三个月把MITM弄坏了两次了，估计这次还是火箭那边的兼容性问题。
