### ISSUE TITLE
小火箭油管去广告-视频开头广告有时可以有时不行

### ISSUE THREAD

**Issue by 100percentXx** [Maasea/sgmodule#39]
主页面广告是完全有效，就是视频开头广告偶尔可以偶尔不行

**Comment by 100percentXx** [comment]
我就是直接把这个surge模块放小火箭里的

**Comment by 100percentXx** [comment]
然后我翻了下大佬之前的议题，看到有个专门给小火箭用的油管去广告模块，我加进去没效果

**Comment by duchenpaul** [comment]
我用的QuantumultX, 几周前youtube更新了, 然后这个去广告啥的都失效了

**Comment by blucewyan** [comment]
小火箭不行了 直接打不开youtube和youtubemusic了

**Comment by Fau818** [comment]
重装YouTube试试

**Comment by General74110** [comment]
可以其他YouTube去广告混用吗

**Comment by a8500830** [comment]
> 如果遇到首页广告正常去除，视频广告无法去除得情况。请查看相关请求里没有 v1/player 这个请求。
> 
> 如果没有v1/player 而是存在v1/get_watch 则是遇到 YouTube 灰度测试。
> 
> 如果遇到 v1/get_watch 得话，请反馈。如果人多得话，后续支持。

确实是新的get_watch，望早日支持

**Comment by Maasea** [comment]
已尝试移除新接口下的播放广告，但与 premium 相关的特性不支持
