### ISSUE TITLE
请问arguments参数如何修改？

### ISSUE THREAD

**Issue by BugGust** [Maasea/sgmodule#43]
例如我需要视频字幕自动翻译为简体中文，不需要移除上传和选段按钮，arguments=后面的参数改如何填写呢？
我尝试过
```
arguments=屏蔽上传按钮:False,屏蔽选段按钮:False,目标翻译语言:zh-CN
```
```
argument="{"targetLang":"{{{zh-CN}}}","blockUpload":{{{False}}},"immersive":{{{False}}}}"
``` 
```
argument=targetLang:zh-CN,blockUpload:False,immersive:False
``` 
都不生效，播放英文视频默认还是英文字幕。

**Comment by Maasea** [comment]
首先你没有更到最新的sgmodule，同时还需要确保一下脚本的 build 时间是最新的，因为GitHub 因为缓存的原因更新不太及时。

如果你需要手动修改argument，其中应该不包含{{{}}} 这样的符号，这是surge 本身需要的替换标识符。

另外，json 中的bool类型应是是小写
```
argument="{"lyricLang":"zh-Hans","captionLang":"zh-Hans","blockUpload":false,"immersive":false}"
```

**Comment by Maasea** [comment]
为了方便你理解给你一个完整的例子：
下面的例子，关闭了Youtube music 的歌词翻译，打开了字幕翻译且翻译语言为简体中文，保留了上传和选段按钮。

```
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting),requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.response.preview.js,argument="{"lyricLang":"off","captionLang":"zh-Hans","blockUpload":false,"immersive":false}"
```

**Comment by Maasea** [comment]
sgmodule 顶部的`#!arguments=屏蔽上传按钮:true,屏蔽选段按钮:true,字幕翻译语言:zh-Hans,歌词翻译语言:zh-Hans`是为了适配最近 surge TF 版本的新特性，可以长按模块使用输入框的形式修改模块。

见下图：
![2024-02-18-21-10-13](https://github.com/Maasea/sgmodule/assets/41108003/b2c49036-d786-40cf-9202-77ab576f821b)

**Comment by BugGust** [comment]
> 为了方便你理解给你一个完整的例子： 下面的例子，关闭了Youtube music 的歌词翻译，打开了字幕翻译且翻译语言为简体中文，保留了上传和选段按钮。
> 
> ```
> youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting),requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.response.preview.js,argument="{"lyricLang":"off","captionLang":"zh-Hans","blockUpload":false,"immersive":false}"
> ```

好的，谢谢dalao了，更新了下外部资源就好了，之前为了修改上传按钮把模块copy到本地了，现在不需要了，我这边没在TF版，所以不清楚新加的特性😂
