### ISSUE TITLE
关于最近一些奇怪的现象,来汇报一下

### ISSUE THREAD

**Issue by EvilCult** [Maasea/sgmodule#46]
### 起因
一段时间前,忽然这个模组就不太好用了,以为是youtube更新的正常情况,过阵子会好.但是并没有.
于是看了下commit发现一直在更新,作者并没有弃坑, 并且翻阅issues发现我的情况好像有点特殊.
于是来汇报一下.

### 具体表现
1. 主页列表的广告依然去除的很干净.
2. 视频开播前的广告有的时候有,有的时候没有.
3. pip功能可用.
4. 背景播放功能失效.(iPhone下拉锁屏界面有一个空的播放器,真的锁屏后视频暂停.)

### 尝试解决方法
1. 更新所有软件到当前appstore里的最新版 : 无效果
2. 重装模组 / 关闭其他模组仅保留一个 : 无效果
3. 设置里打开“代理接管优先” / 代理服务器设置阻止一切quic流量 : 无效果
4. 更换代理服务器: 无效果
5. 重装surge : 无效果
6. 重装youtube : 有效, 无广告,且可以后台播放(锁屏播放).但是,播放几个视频后,就会出现广告,此时后台播放功能同时失效.

### 测试环境
- iOS 17.5 (beta) (21F5048f)
- Surge (5.11.0)
- YouTube (19.16.3)

### 附加
经过多次删除重装YouTube测试, 每次本模组失效时,可以在最近请求里发现一条 MitM Failed的请求,目标地址为以下其中之一: 
```
rr1---sn-najern7k.googlevideo.com:443
rr2---sn-najern7k.googlevideo.com:443
rr3---sn-najern7k.googlevideo.com:443
rr4---sn-najern7k.googlevideo.com:443
``` 
后续针对该url的请求也会出现,大部分正常,MitM Failed的情况则随机出现,
但似乎MitM Failed和广告出现又没有正相关,很奇怪.

按Surge官方说法提示Mitm Failed时表明youtube正使用SSL Pinning机制阻止MITM,似乎无解了.

### 结
以上即我最近遇到的情况,感谢作者做出这样一个方便好用的项目.
祝安好!

**Comment by Maasea** [comment]
首先，如果使用了SSL Pinning 脚本会完全失效，而不会出现偶尔可用偶尔不可用的情况。
出现 MitM Failed 和脚本没有关系，你上述的场景像是触发了surge 的防盗版机制。
如果确认是正版app 的情况下，建议与开发者联系。

**Comment by EvilCult** [comment]
Surge是正版的不会有问题。
不过你这样一讲，我的续订倒是在二月过期了没有续。新功能Body重写没有开通。
不知是否于此有关，我来续订一下试试。

**Comment by EvilCult** [comment]
续订了surge，包括youtube两个app又进行了一次删除重装操作。
结果一样。
视频片头广告时有时无，锁屏无法播放，其余功能正常。

**Comment by Maasea** [comment]
模块没有使用新特性，所以和续订无关。

另外问一下用的是哪里的模块，是本库的还是别人魔改的，又或者使用转换工具转的？

背景播放的问题，有点像上一次修改模块造成的问题但后续又修复了。

在 tg 联系一下我 @BlveRiv

**Comment by EvilCult** [comment]
好的，tg上见。

**Comment by Ao-Last** [comment]
1. 发现同一现象（脚本首次安装后完美运行，此后突然部分失效），不知后续是否解决该问题？
2. 分享一个我的发现，在HTTP Rewrite开启的情况下脚本完美运行；关闭后又出现部分失效（首页无广告，部分视频开头广告仍有，特别是数码博主的视频，上传按钮等去除生效，PIP生效，后台播放失效）
3. 我查看了一下脚本，貌似不涉及到URL Rewrite规则，该脚本应该配合HTTP Rewrite打开使用吗？
