### ISSUE TITLE
QX failed to update with Parser

### ISSUE THREAD

**Issue by kewachan** [Maasea/sgmodule#48]
Sorry that i am using QX but found this sgmodule is really useful, i used Resource Parser to convert this sgmodule for QX but found an error this morning.

Resource parser result with invalid Line ^https?:VVI\w-]+.googlevideo)...

it works perfect before but since today.

understand this is not for Quantumult X, so this is just for an report, hope that there will be one similar plugin specific for QX someday

**Comment by Maasea** [comment]
MAP LOCAL uses a new feature of surge, which you can ask the Parser author to support, or use reject-img instead.
