### ISSUE TITLE
Youtube Module not working!

### ISSUE THREAD

**Issue by duxngkun** [Maasea/sgmodule#51]
I have tried many ways such as deleting and reinstalling, changing many different accounts (including new accounts) but the script still does not work. I wonder if YouTube's new update caused your script to have this problem? I hope you update it, thank you <3

**Comment by duxngkun** [comment]
![image](https://github.com/Maasea/sgmodule/assets/139708676/a777f047-d582-442e-aadf-701c930105e7)

![image](https://github.com/Maasea/sgmodule/assets/139708676/4bc0f632-ab6e-4525-bc82-30138abc707e)

I try running the script and it says this? I don't know what error is being made here!

**Comment by Maasea** [comment]
First of all, all modules are written based on surge features, and it's normal that Shadowrocket can't run compatibly.

You can refer to   #27

**Comment by duxngkun** [comment]
I consulted as you said, but the urls youtube.request.beta.js and youtube.response.beta.js don't exist so it doesn't work. The previous version I used was fine, but because you deleted it, I thought you deleted it. There is a newer update for it but it is not compatible. Can you provide me those 2 files again?

**Comment by Maasea** [comment]
You can find both files in the git history.

**Comment by duxngkun** [comment]
I've only recently used github so I'm not familiar with how to view git history. Can you guide me on this part, thanks.

**Comment by duxngkun** [comment]
Mình hiểu rồi, nó nằm trong phần commit nhưng để xem full code mình nên bấm vào xem file đúng không anh em?

**Comment by duxngkun** [comment]
I understand, it's in the commit section, but to see the full code, I should click to view the file, right?
