### ISSUE TITLE
QuantuX添加模块，报错

### ISSUE THREAD

**Issue by vcdog** [Maasea/sgmodule#52]

**Comment by vcdog** [comment]
![image](https://github.com/Maasea/sgmodule/assets/7135182/a91358ed-fea3-42e3-9d3b-a8d962d0ac33)

**Comment by kewachan** [comment]
You can just create your own local rewrite and use the request and respond js in his script. Works prefect for me in my QX.

**Comment by NeaoSwift** [comment]
> prefect

could you show me your local rewrite pls

**Comment by vcdog** [comment]
![image](https://github.com/Maasea/sgmodule/assets/7135182/3fbdc133-c75b-48e5-b178-313f268aade5)
把data=""修改为上面图片的内容后，再添加qx就可以了。屏蔽广告及窗口都支持。感觉作者提供的链接帮助。

**Comment by vcdog** [comment]
![image](https://github.com/Maasea/sgmodule/assets/7135182/e7722088-5855-480f-97a9-39440c63ac7d)
