### ISSUE TITLE
What does these two rules mean?

### ISSUE THREAD

**Issue by FrontMage** [Maasea/sgmodule#53]
Hi, I'm trying to build my own surge alternative, so I would like to support as much surge rules as I can, but when I'm trying to use these rules, I don't know how to implement them

```
[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT
```

Other rules and functions are implemented, but without these two I still get some ads when playing video

Can you plz help me understand what these rules do? Thx!

**Comment by Maasea** [comment]
These two rules are used to block quic requests from YouTube app and make it fallbacks to HTTP requests.

This is because surge supports mitm over http but not mitm over quic.

**Comment by Maasea** [comment]
Specifically, without the rules above, Youtube would be transmitting the data using the quic protocol.

**Comment by FrontMage** [comment]
Oh, I see, so these are blocking UDP connections that have remote addresses of googlevideo.com and youtubei.googleapis.com? So can I just block these two domains' DNS requests or do I have to maintain an IP to domain hashmap to block the UDP connections only?

**Comment by Maasea** [comment]
Blocking dns requests can't be done because http has the same domain name.

You can only go to block udp requests, or you subject to implement mitm over quic

**Comment by FrontMage** [comment]
Crystal clear! Thx for the help!
