### ISSUE TITLE
更新YouTube版本，发现v1/get_watch

### ISSUE THREAD

**Issue by idjfia** [Maasea/sgmodule#57]
播放去广告和画中画失效

翻看之前议题的好像是被灰度了？还是新版本全面铺开了…

**Comment by Maasea** [comment]
上一次更新 已经解决该问题。

更新一下模块即可

**Comment by Maasea** [comment]
昨晚更新了一次脚本，看下能不能去掉。

关于 rangerror，是因为模块需要匹配 next 请求，但是目前的正则同样会匹配到 next/heartbeat，在反序列化二进制文件的时候出错了。脚本应该做了错误处理，只是输出日志，应该不会有太大的影响。这个错误可能需要维持现状，后续有空调整一下正则。
