### ISSUE TITLE
求YouTube去广告qx版

### ISSUE THREAD

**Issue by chengkongyiban** [Maasea/sgmodule#6]
您的模块我用qx通过资源解析器转到qx去不了广告，小火箭效果完美，求qx的版本。

**Comment by Maasea** [comment]
尝试了一下，quanx 的脚本操作不符合预期。
请手动添加一条重写
```
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad url reject-img
```
另，surge 在频繁拒绝后，reject 会上升到reject-drop。 quanx 如果有同等操作可能会出现频繁切视频导致卡顿。
