### ISSUE TITLE
CC 

### ISSUE THREAD

**Issue by dghnbsa** [Maasea/sgmodule#62]
如果我想关闭 CC，使其不会自动打开，在哪里可以修复它？

**Comment by dghnbsa** [comment]
使用 youtube 模块时关闭 CC

**Comment by Maasea** [comment]
自己改一下参数，模块里有说明

**Comment by dghnbsa** [comment]
我将“zh-Hans”更改为“zh-Hans”\n2，对吧？

**Comment by dghnbsa** [comment]
或者我应该将“zh-Hans”更改为“off”？

**Comment by dghnbsa** [comment]
我做到了，谢谢你的支持，我想结束这个话题。
