### ISSUE TITLE
youtube去广告好像失效了？

### ISSUE THREAD

**Issue by sparkwj** [Maasea/sgmodule#63]
使用小火箭，之前一直可以，前几天开始好像不行了

**Comment by Goooooooooood** [comment]
我也遇到了。前几天youtube灰度热更新导致广告过滤部分失效，后台播放还能用，没热更新的那台手机就正常。后来两台手机都自动热更新了，我降级了youtube版本，去广告依然有效，但评论区经常加载不出来。之前合买过几次YT会员，都是用一阵后商家跑路告终，所以还挺依赖这个项目的。

**Comment by labac-p** [comment]
YouTube 更新了一些内容，导致 Shadowrocket 无法捕获 get_watch 查询，因此无法在播放视频时删除广告。但今天我看到它又正常工作了。

**Comment by Maasea** [comment]
get _watch 早在几个月前就已经适配。目前很没有收到其他app的反馈，尝试使用其他app试试。

如果是新的灰度，当前我无法复现。

**Comment by chengkongyiban** [comment]
如图，似乎是因为这个 ![image](https://github.com/user-attachments/assets/2caec94a-dced-416f-b146-5b88ea3c273f)

**Comment by znlkws** [comment]
也遇到不生效的问题了，回退youtube版本也没用

**Comment by Goooooooooood** [comment]
> 也遇到不生效的问题了，回退youtube版本也没用

YouTube App热更新后，下滑小窗口播放样式会变，变成了一个浮动的窗口，广告过滤会失效。这是一个显著的特征。而老版本的小窗口播放，是停靠在底部的，广告过滤依然有效。看看你是哪一种？

我只回退了一台手机到旧版本App，版本号18.41.2，用了两天，暂时没有被自动热更新。

另一台手机新版本App的广告过滤，依然是失效状态，刚试过。

我是复制了作者代码，只在细微的地方做了一些改变，以适配小火箭。不是用的第三方的过滤模块，那种可能存在代码功能冲突。希望对你有帮助。

**Comment by Maasea** [comment]
> YouTube App热更新后，下滑小窗口播放样式会变，变成了一个浮动的窗口

我现在还是旧版悬浮窗。

听起来应该是数据结构变更了。因为我没有被灰度，所以无法完成脚本更新。 有兴趣的话可以发一个最新的数据包给我，最好能协助测试。

另外，脚本使用request类型清除广告，response用于兜底。不太清楚request逻辑是不是变更了。

**Comment by znlkws** [comment]
> > 也遇到不生效的问题了，回退youtube版本也没用
> 
> YouTube App热更新后，下滑小窗口播放样式会变，变成了一个浮动的窗口，广告过滤会失效。这是一个显著的特征。而老版本的小窗口播放，是停靠在底部的，广告过滤依然有效。看看你是哪一种？
> 
> 我只回退了一台手机到旧版本App，版本号18.41.2，用了两天，暂时没有被自动热更新。
> 
> 另一台手机新版本App的广告过滤，依然是失效状态，刚试过。
> 
> 我是复制了作者代码，只在细微的地方做了一些改变，以适配小火箭。不是用的第三方的过滤模块，那种可能存在代码功能冲突。希望对你有帮助。

感谢, 多回退了几个版本, 变回旧的窗口了, 去广告也正常

**Comment by sparkwj** [comment]
我今天打开也出现了新版的悬浮窗，但是前几天我客户端还是旧版悬浮窗的时候去广告就失效了。另外我发现
https://github.com/YanbingJiang/Shadowrocket_diy_rules/blob/main/Modules/YT-Adblocker.module
这个简单规则的模块在我手机上是可以去youtube广告（新旧悬浮窗都可以，前几天maasea的模块失效的时候这个就可以），似乎也不影响后台播放，但是不能去yt music的广告，而之前maasea的模块yt music这些功能都是好的。我尝试编辑过maasea的规则，去掉script段，似乎也不行，跟前面网址里的规则有些细微差别，具体什么问题我就不知道了。

**Comment by labac-p** [comment]
看来有些视频在调用 /browse API 时已经包含完整的信息。当点击观看视频时，youtube 不会调用 /get_watch 😕

**Comment by ErfanM98** [comment]
I want to report the same issue. I checked with burp suite, it seems that the ads are loading from `browse` API. I think one new item is added to the structure of browse.

**Comment by mottzz87** [comment]
YouTube has no background playback

**Comment by Maasea** [comment]
> I want to report the same issue. I checked with burp suite, it seems that the ads are loading from `browse` API. I think one new item is added to the structure of browse.

Can you upload the browse raw request body and response body?

**Comment by cwyin7788** [comment]
> 使用小火箭，之前一直可以，前几天开始好像不行了

暂时发现了一个半解决方案，广告出现时切换去任意app，然后立刻切换回youtube app，广告就没了，这个方法聊胜于无，至少肯定可以在5秒内完成这样的切换🤣

**Comment by ErfanM98** [comment]
> Quote reply
[youtube.browse.zip](https://github.com/user-attachments/files/17534170/youtube.browse.zip)
 This is broswe raw response.

**Comment by Maasea** [comment]
> > Quote reply
> > [youtube.browse.zip](https://github.com/user-attachments/files/17534170/youtube.browse.zip)
> > This is broswe raw response.
Are you sure this is the browse response body, I checked and it's more like ‘get_watch' and there are no ads in the body.

**Comment by ErfanM98** [comment]
I'll check and upload again

**Comment by litengfei123** [comment]
> 我今天打开也出现了新版的悬浮窗，但是前几天我客户端还是旧版悬浮窗的时候去广告就失效了。另外我发现
> https://github.com/YanbingJiang/Shadowrocket_diy_rules/blob/main/Modules/YT-Adblocker.module
> 这个简单规则的模块在我手机上是可以去youtube广告（新旧悬浮窗都可以，前几天maasea的模块失效的时候这个就可以），似乎也不影响后台播放，但是不能去yt music的广告，而之前maasea的模块yt music这些功能都是好的。我尝试编辑过maasea的规则，去掉script段，似乎也不行，跟前面网址里的规则有些细微差别，具体什么问题我就不知道了。

这个确实可以 老哥稳

**Comment by wei954** [comment]
YouTube 怎么降级，有没有大佬解答一下，我是 ios

**Comment by YanbingJiang** [comment]
发现在最新小火箭版本下(2.2.57(2440))，YT老版本(我的版本是19.30.2)，在Shadowrocket - 设置 - 代理 - 代理类型 - 选择 None (TUN Mode)，脚本又会生效 (广告去除后台也可以播放了，我之前选在了HTTP就失效了)。YT最新版本(19.45.*) 选择哪个都无效了。

感觉小火箭那里应该也有bug，不是很确定。

**Comment by ErfanM98** [comment]
Today with the latest versions of both YouTube and Shadowrocket I can see no ads on the app. I think it was a bug in Shadowrocket but I'm not sure either.

**Comment by sparkwj** [comment]
应该是小火箭的问题，我这里更新后也好了

**Comment by wei954** [comment]
是不是小火箭的问题，油管更新后模块失效了？现在有广告非常难受

**Comment by YanbingJiang** [comment]
@sparkwj @wei954 小火箭刚刚更新到2.2.58(2441), 确认Shadowrocket - 设置 - 代理 - 代理类型 - 恢复到默认Http之后，实验了一下最新版和老版本YT都没有问题了。
