### ISSUE TITLE
YouTube Music 解锁会员失败

### ISSUE THREAD

**Issue by lightingteeth** [Maasea/sgmodule#69]
问题如[#68](https://github.com/Maasea/sgmodule/issues/68)所述，今早再使用小火箭发现也同样失效了，总结一下问题：

1. 可以单独播放单个的音乐，但是歌曲和显示的音乐名不符，并且播放列表也一直没有变动
2. 抓包发现偶尔有mitm失败的情况：报错信息为：
12:39:39.416342 [Connection] Handled by VIF
12:39:39.422997 [TLS] TLS Client Hello SNI: rr1---sn-ogueln67.googlevideo.com
12:39:39.424343 [MITM] Enable MITM due to MITM hostname settings entry: *.googlevideo.com (Youtube (Music) Enhance)
12:39:39.428351 [MITM] MITM via HTTP/1.1 mode
12:43:17.691841 [MITM] MITM failed. Client closed connection just after TLS handshake, it might because of certificate pinning.
12:43:56.538092 [Connection] Handled by VIF
12:43:56.543995 [TLS] TLS Client Hello SNI: rr2---sn-oguesnde.googlevideo.com
12:43:56.545398 [MITM] Enable MITM due to MITM hostname settings entry: *.googlevideo.com (Youtube (Music) Enhance)
12:43:56.551336 [MITM] MITM via HTTP/1.1 mode
12:45:35.457672 [MITM] MITM failed. Client closed connection just after TLS handshake, it might because of certificate pinning.
3. 音乐可以在后台播放，但是灵动岛上并不显示歌曲的图片![image](https://github.com/user-attachments/assets/c63c1646-ecd2-4735-b8b1-84681b1b011e)

**Comment by Maasea** [comment]
MITM 失败无关脚本
其他描述未复现
