### ISSUE TITLE
Youtube去广告surge模块在iPad端异常

### ISSUE THREAD

**Issue by Meonthb** [Maasea/sgmodule#7]
Youtube去广告模块在iPhone端表现正常，但在iPad端会出现整页白屏，下拉很久才有内容，然后再下拉又是白屏，如此反复，如图所示：

![](https://i.imgur.com/npEWqfr.jpg)

**Comment by Maasea** [comment]
已知bug，该页面的适配由 [smile](https://github.com/app2smile/rules) 的项目完成。
我询问过原作者，原作者无 IPad ，无法进行修复。
后续我随缘尝试适配

**Comment by Maasea** [comment]
已修复，需更新模块和脚本
